Fix scbk reference state
goodchemistryco/Tangelo pull request #176
Opened 2022-07-20 16:33 UTC by JamesB-1qbit

There are two Bravyi-Kitaev transformations that are different if the number of qubits is not a power of 2. The current implementation used `bravyi_kitaev` for the reference state and `bravyi_kitaev_tree` for the SCBK mapping causing issues in certain instances. The example I came across was 
`mol = SecondQuantizedMolecule(xyz_H2O, 0, 0, "sto-3g", frozen_orbitals=[0, 7])`
which is now tested and passes.

2022-07-21 13:14 UTC, AlexandreF-1qbit approved these changes
Thanks for the fix!

2022-07-21 22:02 UTC, ValentinS4t1qbit requested changes
A few things to clean up

2022-07-22 18:49 UTC, JamesB-1qbit commented on tangelo/toolboxes/qubit_mappings/statevector_mapping.py
> +from openfermion import QubitOperator
Our QubitOperator does not multiply with the openfermion QubitOperator. It fails at the check of the class in the openfermion QubitOperator `__mul__` code. Is there an easy way to fix this. Or should I just copy that code into our QubitOperator class.

2022-07-22 18:50 UTC, JamesB-1qbit commented on tangelo/toolboxes/qubit_mappings/statevector_mapping.py
> +from openfermion.transforms import bravyi_kitaev_code
It is used in the bravyi kitaev vector transform.

2022-07-27 20:13 UTC, ValentinS4t1qbit commented on tangelo/toolboxes/qubit_mappings/statevector_mapping.py
> +from openfermion import QubitOperator
You're right. Since we already import several functions from openfermion, I don't see the point of not importing their qubitoperator directly.

2022-07-28 17:20 UTC, ValentinS4t1qbit approved these changes
Good job :)

2022-07-28 17:21 UTC, merged