Add gates ionq
goodchemistryco/Tangelo pull request #212
Opened 2022-09-15 13:28 UTC by JamesB-1qbit

Add controlled rotations, swap, and phase gates. Tested on IonQ noisy simulator.

2022-09-15 18:25 UTC, AlexandreF-1qbit approved these changes

2022-09-16 22:26 UTC, ValentinS4t1qbit requested changes
I think we can simplify things a bit on the translator side.
Thanks for looking into this, this is definitely an improvement in both features and I believe simplicity as well :)

2022-09-16 22:26 UTC, ValentinS4t1qbit commented on tangelo/linq/translator/translate_json_ionq.py
> +            json_gates.append({'gate': GATE_JSON_IONQ[gate.name], 'targets': gate.target})
I'm a bit confused here. I have a feeling we are only dealing with 4 different situations:

- A list of gates that take no control, no parameters (SWAP, X, Y, Z, H, S, T)
- A list of gates that take parameters but no controls (RX, RY, RZ, PHASE, XX)
- A list of gates that take controls but no parameters (CX, CY, CZ, CNOT)
- A list of gates that take both (CRX, CRY, CRZ, CPHASE)

Couldn't we refactor this to only have 4 branches, now that controls and targets keywords are used everywhere ?

2022-09-16 22:26 UTC, ValentinS4t1qbit commented on tangelo/linq/tests/test_translator.py
> +                                   {'controls': [0], 'gate': 'x', 'targets': [1]},
Could we respect order here and start with gate name, for readability ?

2022-09-22 17:10 UTC, ValentinS4t1qbit approved these changes
Thanks, looks good !

2022-09-22 17:11 UTC, merged