Uhf reference [WIP]
goodchemistryco/Tangelo pull request #240
Opened 2022-10-25 17:03 UTC by JamesB-1qbit

Support for UHF reference in SecondQuantizedMolecule.
Works for VQESolver, all ansatz except VSQS and CCSDSolver.

2022-11-24 15:16 UTC, AlexandreF-1qbit requested changes

2022-11-24 15:16 UTC, AlexandreF-1qbit commented on tangelo/algorithms/classical/fci_solver.py
> +from xml.dom import NotSupportedErr
Is this import used?

2022-11-24 15:16 UTC, AlexandreF-1qbit commented on tangelo/algorithms/variational/tests/test_vqe_solver.py
> +        """Run VQE on H4 molecule, with UCCSD ansatz, JW qubit mapping, initial parameters, exact simulator """
Mapping is scBK in the test.

2022-11-24 15:17 UTC, AlexandreF-1qbit commented
Also, just for the comment, I saw that it is the `FCISolver` that does not support UHF in this implementation, not `CCSDSolver`.

2022-11-25 04:29 UTC, ValentinS4t1qbit requested changes
Minor changes, looks good so far.

2022-11-25 04:35 UTC, ValentinS4t1qbit commented on tangelo/toolboxes/molecular_computation/molecule.py
> +            return [int(sum([self.mo_occ[0][i] for i in self.active_occupied[0]])), int(sum([self.mo_occ[1][i] for i in self.active_occupied[1]]))]
can't we just use self.n_active_electrons here ?

2022-11-28 15:25 UTC, ValentinS4t1qbit requested changes

2022-11-28 15:25 UTC, ValentinS4t1qbit commented on tangelo/toolboxes/molecular_computation/molecule.py
> +                   f"The new molecular coefficients has shape {[new_mo_coeff[0].shape, new_mo_coeff[1].shape]}"\
have shape

2022-11-28 15:25 UTC, ValentinS4t1qbit commented on tangelo/toolboxes/molecular_computation/molecule.py
> +                                 all(isinstance(_, (int, np.integer)) for _ in frozen_orbitals[0])):
This looks like an extra copy-paste. This line is difficult to parse but that `all(isinstance(_, (int, np.integer)) for _ in frozen_orbitals[0]` may not be necessary.

2022-11-28 15:25 UTC, ValentinS4t1qbit commented on tangelo/toolboxes/molecular_computation/molecule.py
> +        if self.uhf:
How about grouping some of them to avoid a big blob ofl ines defining a list each ?

`occupied, virtual = [], []` etc.

2022-11-28 17:24 UTC, JamesB-1qbit commented on tangelo/toolboxes/molecular_computation/molecule.py
> +        self.mean_field.analyze()
I believe it is required to check implement the check
```python3
if not self.mean_field.converged:
    raise ValueError("Hartree-Fock calculation did not converge")
```

2022-11-28 18:52 UTC, ValentinS4t1qbit approved these changes

2022-11-28 18:56 UTC, AlexandreF-1qbit approved these changes

2022-11-28 19:11 UTC, merged