Function that returns the qubits used for Truncated Taylor Series
goodchemistryco/Tangelo pull request #339
Opened 2023-09-14 18:45 UTC by JamesB-1qbit

A simple function that pre-computes the qubits used when calling the `get_truncated_taylor_series` function.

2023-09-14 22:00 UTC, ValentinS4t1qbit requested changes
Just a small inconsistency in the docstring

2023-09-14 22:00 UTC, ValentinS4t1qbit commented on tangelo/toolboxes/circuits/lcu.py
> +        t (float): The evolution time
does not match your function signature

2023-09-15 13:08 UTC, AlexandreF-1qbit approved these changes

2023-09-19 16:48 UTC, ValentinS4t1qbit approved these changes
Thank you for this contribution !

2023-09-19 16:48 UTC, merged