Helper class and functions for iFCI fragment import
goodchemistryco/Tangelo pull request #351
Opened 2023-10-23 19:36 UTC by AlexandreF-1qbit

*Highlights*
- Add support for iFCI fragments. Mostly, it is just a manner of supporting `correction=0.` for each term. The rest was renaming the class and adapting the documentation.
- Fixed the import function with the new QEMIST Cloud outputs.
- Tests for iFCI and MIFNO with new QEMIST Cloud outputs.

2023-10-25 04:02 UTC, ValentinS4t1qbit requested changes
Small changes, otherwise all good !

Since people know us for MI-FNO and iFCI I think we need to mention the terms at least in the main docstrings of your helper to be crystal clear from the start. By extension this applies to our notebook in your other PR: we should probably rename it mifno_ifci, highlight both acronyms in the intro (opportunity for us to link to something good about IFCI PFAS), and adjust the link in contents.rst

Question: are we then handling both MIFNO and iFCI jobs the same way, without distinction ? From what I've read in this PR one could infer Q.Cloud computed things differently and MIFNO applied a MP2 correction but iFCI did not.

2023-10-25 20:27 UTC, AlexandreF-1qbit commented on tangelo/problem_decomposition/incremental/incremental_helper.py
> +"""This file provides helpers in order to import data coming from an incremental
I added the acronyms and references.

2023-10-25 20:29 UTC, AlexandreF-1qbit commented on tangelo/problem_decomposition/incremental/incremental_helper.py
> +            raise FileNotFoundError(f"The {source_folder} path does not exist.")
The error message is not printing the absolute path. When a user is giving an absolute path, the `absolute_path = os.path.abspath(destination_folder)` line just does nothing.

2023-10-25 20:33 UTC, AlexandreF-1qbit commented
For your question in the top comment, MIFNO and IFCI are indeed handled in the same way. For iFCI, there is no correction term. The MO coefficient are different, as iFCI has a better way of handling orbitals and the truncation scheme is "exact" within the approximations they are working with.

2023-10-26 03:51 UTC, ValentinS4t1qbit commented on tangelo/problem_decomposition/incremental/incremental_helper.py
> +            raise FileNotFoundError(f"The {source_folder} path does not exist.")
Ok :)

My suggestions remain the same, here

2023-10-26 14:22 UTC, AlexandreF-1qbit commented
I added two tests for the `retrieve_mo_coeff` method. The `compute_fermionoperator` is not included in the test, as the underlying mechanisms of computer a fermionic operator is already tested in `SecondQuantizedMoleculeTests`.

2023-10-29 16:30 UTC, ValentinS4t1qbit approved these changes
Thank you Alexandre ! We'll figure out the qiskit issues separately, I see no reason to delay this.

2023-10-29 16:31 UTC, merged