Added support for multi-controlled gates on qiskit
goodchemistryco/Tangelo pull request #390
Opened 2024-05-29 06:02 UTC by golanor

Added support for multi-controlled gates on qiskit, see #387

2024-05-29 14:37 UTC, ValentinS4t1qbit requested changes
Thank you, this looks good ! You even supported an extra gate ! The test is convincing. 

- I think some imports can be cleaned up.
- One of the checks currently fails (`pycodestyle` says theres a trailing white space somewhere). Some other checks fail but I don't think it is related to your contribution and we know why.

Out of curiosity: would considering the CRX, CRY, etc as MCRX, MCRY, ... with a single control qubit be possible ? This would simplify the code, and then we may not even need the `crx`, `cry`, `crz`, gate from Qiskit in the dictionary.

It may be that if a user passes a single integer in the Tangelo gate, the software automatically converts it into a list of 1 element. In that case, the the full list of control qubits can always be passed in the translation.

If I am wrong and this becomes tricky, we can forget about this improvement.

2024-05-29 14:37 UTC, ValentinS4t1qbit commented on tangelo/linq/tests/test_translator_circuit.py
> +        from tangelo.linq import Gate, Circuit, translate_circuit
All of these have been imported already at the beginning of the module, I think they can be removed (L25)

2024-05-29 14:50 UTC, golanor commented
> Out of curiosity: would considering the CRX, CRY, etc as MCRX, MCRY, ... with a single control qubit be possible ? This would simplify the code, and then we may not even need the `crx`, `cry`, `crz`, gate from Qiskit in the dictionary.
> 
> It may be that if a user passes a single integer in the Tangelo gate, the software automatically converts it into a list of 1 element. In that case, the the full list of control qubits can always be passed in the translation.
> 
> If I am wrong and this becomes tricky, we can forget about this improvement.

It depends on the end realization - the compilation of the MCR() gates is wasteful compared to the CR() gates. If that doesn't matter then we can probably change it.

Regarding the trailing whitespace - I haven't found where it is happening, or which action fails. Can you please point me to where to find it?

2024-05-29 16:28 UTC, ValentinS4t1qbit commented
> It depends on the end realization - the compilation of the MCR() gates is wasteful compared to the CR() gates. If that doesn't matter then we can probably change it.

Then I do not mind leaving them alone, the code is still pretty simple. Thanks for the insight.

> Regarding the trailing whitespace - I haven't found where it is happening, or which action fails. Can you please point me to where to find it?

Unexpected: in an unrelated file outside of your PR, I see a whitespace in the printing format. Our linter complains about it.
Would you please remove that whitespace ? This way all tests should pass and we're calling this PR done !

../tangelo/algorithms/variational/adapt_vqe_solver.py:322:61: E203 whitespace before ':'

I saw that while checking the list of checks at the bottom of this PR page, and clicking "details".
Out of curiosity, are you able to click and access the details of the checks ? It would be troublesome if our users could not see them.

<img width="917" alt="Screenshot 2024-05-29 at 6 26 56 PM" src="https://github.com/goodchemistryco/Tangelo/assets/41597680/45145d3f-de4f-4594-8e59-3cf30edf7ada">

Thank you so much, appreciate your patience on this. Unexpected things happen :)

2024-05-29 17:46 UTC, golanor commented
> Unexpected: in an unrelated file outside of your PR, I see a whitespace in the printing format. Our linter complains about it. Would you please remove that whitespace ? This way all tests should pass and we're calling this PR done !
> 
> ../tangelo/algorithms/variational/adapt_vqe_solver.py:322:61: E203 whitespace before ':'
> 
> I saw that while checking the list of checks at the bottom of this PR page, and clicking "details". Out of curiosity, are you able to click and access the details of the checks ? It would be troublesome if our users could not see them.

> Thank you so much, appreciate your patience on this. Unexpected things happen :)

I only now realized I can scroll down the checks and see the ones that failed... 

Thank you for being so available! I fixed the whitespace issue.

2024-05-29 18:12 UTC, ValentinS4t1qbit requested changes
A small final change and the bounty is yours ! 

Your import was already available as a slightly different name, we do not need imports inside that function (in general we prefer to import at the beginning of the module, rather than re-importing inside each function that needs it).

The checks have all passed, so I'm sure it will all work out after your next change.

2024-05-29 18:12 UTC, ValentinS4t1qbit commented on tangelo/linq/tests/test_translator_circuit.py
> +        from tangelo.linq import translate_circuit
This function was already imported as `translate_c` earlier in the file, we can just reuse that and remove this line :)

2024-05-30 08:23 UTC, ValentinS4t1qbit approved these changes
Looks good to me !

Thank you for your contribution, I hope this was an interesting experience.
The devil's in the details, and details accumulate over time and make open-source codebase challenging... thank you for your patience :)

If you think Tangelo is an interesting project, please don't hesitate to give us a little ⭐ a consider mentioning it or using it :)

2024-05-30 08:26 UTC, merged