Improving draw method
goodchemistryco/Tangelo pull request #391
Opened 2024-05-29 06:44 UTC by anushkrishnav

First-time contributor here !! Pretty interesting projects 

I have worked on fixing the bug: Circuit. draw() returns an error when the gate parameter is a string
It was a straightforward task and didn't take a lot of time, I have also written the code with spend in mine, For a 100 gate it takes less than a second to draw the output, I have not written a test or doc wanted to get the teams approval after which will finish up with test cases for the draw and _string_to_sympy methods.

The attached collab will give an example of the newer code in motion, I have created a random gate generator that generates n gates( currently set to 100 and n_qubits =2) 
Link: 

Fix for Issue: #388

2024-05-29 14:50 UTC, ValentinS4t1qbit requested changes
Good stuff ! The results look good and if you make these small changes and the automated tests pass, we're good !
I hope this first contribution is a good time so far

The automated tests currently fail because our linter, pycodetest, sees a few things

https://github.com/goodchemistryco/Tangelo/actions/runs/9281488084/job/25537568509?pr=391

```
../tangelo/linq/circuit.py:34:1: E303 too many blank lines (3)
../tangelo/linq/circuit.py:192:1: W293 blank line contains whitespace
../tangelo/linq/circuit.py:214:5: E303 too many blank lines (2)
- generated xml file: /home/runner/work/Tangelo/Tangelo/dev_tools/junit/pycodestyle-test-results.xml -
=========================== short test summary info ============================
FAILED test_conformance.py::TestCodeFormat::test_conformance - AssertionError: 3 != 0 : Found code style errors and warnings.
```

2024-05-29 17:41 UTC, anushkrishnav commented on tangelo/linq/circuit.py
> +    def old_draw(self):
Awesome will finish the docstring and test in a few hrs and send the final commit

2024-05-30 03:37 UTC, anushkrishnav commented
> ../tangelo/linq/circuit.py:192:1: W293 blank line contains whitespace

Had a good time working on the PR, its an interesting projects will keep working on the other issues on board as well. I am aware of the lining issue, wanted to know if i was in the right direction , will finish up the code now

2024-05-30 03:47 UTC, anushkrishnav commented on tangelo/linq/circuit.py
> +        circuit_copy = copy.deepcopy(self)
Got it will use the exsisting ones

2024-05-30 07:59 UTC, ValentinS4t1qbit approved these changes
Looks good to me !

2024-05-30 08:18 UTC, merged

2024-05-30 08:20 UTC, ValentinS4t1qbit commented
Thank you so much for your contributions @anushkrishnav ! I hope this has been an interesting experience, and that you have a learnt a few new things :)

2024-05-30 08:29 UTC, anushkrishnav commented
I have left a star thanks for the support, will start working on the next issue, is there anything needed from my side for the unitary hacks ?